#!/bin/bash

set -e

export SPARK_HOME=~/spark-2.2.0-bin-hadoop2.7
export BigDL_HOME=~/dist-spark-2.2.0-scala-2.11.8-all-0.6.0-dist

MY_PATH="`dirname \"$0\"`"

export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS="notebook --allow-root --notebook-dir=./ --ip=* --no-browser --certfile=${MY_PATH}/mycert.pem --keyfile=${MY_PATH}/mykey.key"
VERSION=0.6.0

source /root/.bashrc
source activate py35

tensorboard --logdir=/tmp/bigdl_summaries/lenet5-  2>&1 >tensorboard.log &

if [ -z "$CORES" ]; then
    CORES=2
fi

${SPARK_HOME}/bin/pyspark \
  --master local[$CORES] \
  --driver-memory 5g \
  --properties-file ${BigDL_HOME}/conf/spark-bigdl.conf \
  --py-files ${BigDL_HOME}/lib/bigdl-${VERSION}-python-api.zip \
  --jars ${BigDL_HOME}/lib/bigdl-SPARK_2.2-${VERSION}-jar-with-dependencies.jar \
  --conf spark.driver.extraClassPath=${BigDL_HOME}/lib/bigdl-SPARK_2.2-${VERSION}-jar-with-dependencies.jar \
  --conf spark.executor.extraClassPath=${BigDL_HOME}/lib/bigdl-SPARK_2.2-${VERSION}-jar-with-dependencies.jar
