FROM continuumio/miniconda
WORKDIR /usr/src/app
COPY jupyter_notebook_config.py ./
COPY install-py35.sh ./
RUN /bin/bash install-py35.sh
RUN rm ./install-py35.sh
COPY start-notebook ./
COPY my* ./
ADD ./notebooks ./notebooks
CMD ["/bin/bash", "start-notebook"]
