FROM continuumio/miniconda
WORKDIR /usr/src/app
COPY jupyter_notebook_config.py ./
COPY install-py35.sh ./
RUN /bin/bash install-py35.sh
RUN rm ./install-py35.sh
COPY start-notebook-py35 ./
WORKDIR /host
CMD ["/bin/bash", "/usr/src/app/start-notebook-py35"]
