FROM continuumio/miniconda
WORKDIR /usr/src/app
COPY jupyter_notebook_config.py ./
COPY install-bigdl-0.3-py27.sh ./
RUN /bin/bash install-bigdl-0.3-py27.sh
RUN rm install-bigdl-0.3-py27.sh
COPY start-notebook-py35 ./
WORKDIR /host
CMD ["/bin/bash", "/usr/src/app/start-notebook-py35"]
