#!/bin/bash

docker run -p 8001:8888 -p 6001:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2
docker run -p 8002:8888 -p 6002:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2
docker run -p 8003:8888 -p 6003:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2
docker run -p 8004:8888 -p 6004:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2
docker run -p 8005:8888 -p 6005:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2
docker run -p 8006:8888 -p 6006:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2
docker run -p 8007:8888 -p 6007:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2
docker run -p 8008:8888 -p 6008:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2
docker run -p 8009:8888 -p 6009:6006 --restart always  --env CORES=4 -dit kalininalex/lenet-bigdl:latest2


